'use client';

import { useState, useSyncExternalStore } from 'react';
import { Slider } from '@/components/ui/slider';
import data from '@/lib/story-data.json';

const subscribe=(callback:()=>void)=>{const media=window.matchMedia('(max-width:700px)');media.addEventListener('change',callback);return ()=>media.removeEventListener('change',callback);};
export const useCompactChart=()=>useSyncExternalStore(subscribe,()=>window.matchMedia('(max-width:700px)').matches,()=>false);

export function StoryGeneralization({locale}:{locale:'pt'|'en'}) {
  const t=(pt:string,en:string)=>locale==='pt'?pt:en;
  const [index,setIndex]=useState(4);
  const [guess,setGuess]=useState<number|null>(null);
  const guesses=[t('Vai continuar alto','It will stay high'),t('Vai cair de novo','It will fall again'),t('Não sei ainda','I am not sure')];
  const compact=useCompactChart();
  const row=data.curve[index];
  const revealed=guess!==null;
  const visible=data.curve.slice(0,revealed?22:12);
  const W=compact?360:820,H=compact?310:360,left=compact?40:52,right=W-20,bottom=H-40;
  const x=(p:number)=>left+Math.log(p/16)/Math.log(1280/16)*(right-left);
  const y=(err:number)=>bottom-err/.9*(bottom-28);
  const line=(key:'test_error_median'|'train_error_median')=>visible.map((d,i)=>`${i===0?'M':'L'}${x(d.width)},${y(d[key])}`).join(' ');
  const band=visible.map((d,i)=>`${i===0?'M':'L'}${x(d.width)},${y(d.test_error_q25)}`).join(' ')+' '+[...visible].reverse().map(d=>`L${x(d.width)},${y(d.test_error_q75)}`).join(' ')+' Z';
  const percent=(v:number)=>(v*100).toLocaleString(locale==='pt'?'pt-BR':'en',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
  return <section className="story-section" id="generalization" aria-labelledby="generalization-title">
    <div className="story-prose"><p className="r-kicker">{t('Avaliar o aprendizado','Evaluating learning')}</p><h2 id="generalization-title">{t('Como a regra se comporta com dados novos','How the rule performs on new data')}</h2><p>{t('A contagem de acertos nas flores mostra como os métodos se saíram nos dados usados para ajustar a regra. Ainda falta saber se ela funciona em outras flores. Essa capacidade de lidar com casos novos é chamada de generalização, e sua avaliação exige separar os exemplos usados no treinamento daqueles reservados para o teste.','The flower accuracy count shows how the methods performed on the data used to fit the rule. We still need to know whether it works on other flowers. This ability to handle new cases is called generalization, and assessing it requires keeping test examples separate from those used in training.')}</p><p>{t('Em 1994, Cheng e Titterington já discutiam o risco de uma rede se adaptar às particularidades da amostra e perder qualidade fora dela. Um modelo muito simples pode não captar o padrão, enquanto outro mais flexível pode ajustar detalhes que não se repetem em novos casos. Trabalhos posteriores investigaram o que acontece quando essa flexibilidade aumenta ainda mais. O próximo exemplo mostra um desses comportamentos, conhecido como double descent.','In 1994, Cheng and Titterington were already discussing the risk of a network fitting a sample’s peculiarities and performing poorly outside it. A simple model may miss the pattern, while a more flexible one may fit details that do not recur in new cases. Later work examined what happens when flexibility increases further. The next example shows one such behavior, known as double descent.')}</p></div>
    <div className="story-lab descent-lab">
      <header className="story-lab-heading"><h3>{t('Comparando modelos no mesmo conjunto de teste','Comparing models on the same test set')}</h3><p>{t('Para essa comparação, passamos das medidas das flores para imagens de dígitos escritos à mão. Cada imagem tem 64 pixels, e a intensidade de cada pixel vira uma entrada do modelo. As imagens e a divisão entre treino e teste permanecem fixas; o que varia é o número de características internas calculadas a partir desses pixels.','For this comparison, we move from flower measurements to images of handwritten digits. Each image has 64 pixels, and each pixel’s intensity becomes a model input. The images and the training/test split stay fixed; what varies is the number of internal features computed from those pixels.')}</p></header>
      <div className="digit-split">{(['train','test'] as const).map(group=><div key={group}><p><strong>{group==='train'?'300':t('1.497','1,497')}</strong> {group==='train'?t('para aprender','to learn from'):t('guardados para testar','held out for testing')}</p><div className="digit-strip">{data.digits[group].map(d=><figure key={d.index}><svg viewBox="0 0 8 8" shapeRendering="crispEdges" aria-label={`${t('Dígito real','Real digit')} ${d.label}`}>{d.pixels.map((v,i)=><rect key={i} x={i%8} y={Math.floor(i/8)} width="1" height="1" fill={`rgb(${255-v*12},${254-v*11},${249-v*12})`}/>)}</svg><figcaption>{d.label}</figcaption></figure>)}</div><small>{t('Seis imagens desse grupo; rótulos reais, não previsões.','Six images from this group; actual labels, not predictions.')}</small></div>)}</div>
      <div className="chart-heading"><span>{t('Dígitos classificados incorretamente (%) ↓ menor é melhor','Misclassified digits (%) ↓ lower is better')}</span><div className="story-legend"><span className="legend-a">━ {t('teste','test')}</span><span className="legend-green">┄ {t('treino','training')}</span></div></div>
      <figure className="descent-chart"><svg viewBox={`0 0 ${W} ${H}`} aria-labelledby="descent-chart-title"><title id="descent-chart-title">{t('Erro de treino e teste por largura do modelo. A faixa mostra o intervalo interquartil de dez inicializações.','Training and test error by model width. The band shows the interquartile range of ten initializations.')}</title>
        {[0,.2,.4,.6,.8].map(v=><g key={v}><line x1={left} y1={y(v)} x2={right} y2={y(v)} className="story-grid"/><text x={left-12} y={y(v)+5} textAnchor="end">{Math.round(v*100)}</text></g>)}
        {[16,128,300,1280].map(p=><text key={p} x={x(p)} y={H-12} textAnchor={p===1280?'end':p===16?'start':'middle'}>{p}</text>)}
        <line x1={x(300)} y1="28" x2={x(300)} y2={bottom} className="interpolation-marker"/>
        <path d={band} className="error-band"/><path d={line('test_error_median')} className="test-curve"/><path d={line('train_error_median')} className="train-curve"/>
        <line x1={x(row.width)} y1={y(row.test_error_median)} x2={x(row.width)} y2={bottom} className="selected-width"/>
        <circle cx={x(row.width)} cy={y(row.test_error_median)} r="7" className="selected-error"/>
      </svg><figcaption>{t('Características internas do modelo · escala logarítmica','Internal model features · logarithmic scale')}</figcaption></figure>
      <div className="descent-readout" aria-live="polite"><div><span>{t('Características','Features')}</span><strong>{row.width}</strong></div><div><span>{t('Erro no treino','Training error')}</span><strong>{percent(row.train_error_median)}</strong></div><div><span>{t('Erro no teste','Test error')}</span><strong className="test-value">{percent(row.test_error_median)}</strong></div></div>
      <div className="capacity-control"><label id="capacity-label">{t('Mude o tamanho do modelo','Change the model size')}</label><Slider min={0} max={revealed?21:11} step={1} value={[index]} aria-labelledby="capacity-label" onValueChange={v=>setIndex(Array.isArray(v)?v[0]:v)}/><div className="story-actions"><button onClick={()=>setIndex(4)}>128</button><button onClick={()=>setIndex(11)}>300</button>{revealed&&<button onClick={()=>setIndex(21)}>{t('1.280','1,280')}</button>}</div></div>
      <p className="curve-explanation" aria-live="polite">{row.width<300?t('Nesta parte da curva, o erro de teste primeiro diminui e depois cresce conforme o modelo se aproxima de 300 características. Com 128, o erro mediano de classificação no treino já é zero, mas cerca de um em cada dez dígitos do teste ainda recebe a resposta errada. Os acertos no treino, sozinhos, não mostram essa diferença.','In this part of the curve, test error first falls and then rises as the model approaches 300 features. At 128, median training classification error is already zero, but roughly one in ten test digits still receives the wrong answer. Training accuracy alone does not show this difference.'):row.width===300?t('Com 300 características, o erro de teste dispara. Aqui o modelo também consegue ajustar praticamente de forma exata os escores usados no treino. São duas noções diferentes de “acertar tudo”.','At 300 features, test error shoots up. Here the model also fits the training scores almost exactly. Those are two different meanings of “getting everything right”.'):t('Depois do pico, o erro em exemplos novos volta a cair. Nesta experiência, o modelo maior termina melhor que o melhor ponto anterior ao pico. É a segunda descida.','Past the peak, error on new examples falls again. In this experiment, the larger model ends up better than the best point before the peak. That is the second descent.')}</p>
      {!revealed?<div className="prediction-pause"><h3>{t('E depois de 300?','What happens after 300?')}</h3><p>{t('Antes de abrir o resto da curva: você acha que o erro em dígitos novos vai continuar alto ou voltar a cair?','Before opening the rest of the curve: do you think error on new digits will stay high or fall again?')}</p><div className="story-actions">{guesses.map((label,i)=><button key={i} onClick={()=>{setGuess(i);setIndex(21)}}>{label}</button>)}</div></div>:<div className="prediction-pause" aria-live="polite"><p className="r-kicker">Double descent</p><h3>{t('O erro volta a diminuir depois do pico','Error falls again after the peak')}</h3><p>{t('Sua hipótese','Your guess')}: {guesses[guess]}. {t('Ao ampliar a comparação, aparece uma segunda queda no erro de teste. Esse resultado ajuda a entender por que a relação entre tamanho e desempenho é mais complexa do que a descrição clássica sugere. Ele depende, porém, do modelo, dos dados e do modo de ajuste. Não significa que aumentar qualquer rede melhore sua resposta ou elimine a necessidade de avaliar casos novos.','Extending the comparison reveals a second drop in test error. This helps explain why the relationship between size and performance can be more complex than the classical account suggests. The result does depend on the model, data and fitting procedure, though. It does not mean that enlarging any network improves its predictions or removes the need to evaluate new cases.')}</p><button onClick={()=>{setGuess(null);setIndex(4)}}>{t('Rever a pergunta','Revisit the question')}</button></div>}
      <details className="story-details"><summary>{t('Como o experimento foi feito e seus limites','How the experiment was run and its limits')}</summary><p>{t('A linha é a mediana de dez inicializações; a faixa cobre os 50% centrais dos resultados. A divisão foi fixa: 300 imagens para treino, 1.497 para teste, sem sobreposição. Os números vêm do experimento local, não de uma curva desenhada à mão.','The line is the median of ten initializations; the band covers the middle 50% of results. The split was fixed: 300 training images, 1,497 test images, with no overlap. These numbers come from the local experiment, not a hand-drawn curve.')}</p><p>{t('O modelo tem uma camada ReLU aleatória e congelada. Só a saída linear é ajustada por mínimos quadrados de norma mínima. Em 128 características, o erro mediano de classificação no treino zera; em 300, a perda quadrática fica praticamente zero. A linha tracejada vertical marca esse segundo evento. Não treinamos uma rede profunda por retropropagação aqui.','The model has a random, frozen ReLU layer. Only the linear output is fitted by minimum-norm least squares. At 128 features, median training classification error reaches zero; at 300, squared loss becomes practically zero. The vertical dashed line marks this second event. We are not training a deep network by backpropagation here.')}</p><p>{t('Uma base pequena e uma única divisão não representam todos os problemas. O resultado demonstra um regime em que a segunda descida existe.','One small dataset and a single split do not represent every problem. The result demonstrates one regime in which the second descent exists.')}</p><div className="source-links"><a href="/data/double-descent.json" download>{t('Dados completos e configuração ↓','Full data and configuration ↓')}</a><a href={data.sources.digits} target="_blank" rel="noreferrer">Digits ↗</a><a href="https://doi.org/10.1073/pnas.1903070116" target="_blank" rel="noreferrer">Belkin et al., 2019 ↗</a></div></details>
    </div>
  </section>;
}
