'use client';

import { useMemo, useState } from 'react';
import { Slider } from '@/components/ui/slider';
import { damage, memory, recover } from '@/lib/hopfield.mjs';

const judgments=[
  {
    label:['Aprender com o erro','Learning from error'], pages:'17, 19, 26',
    question:['A retropropagação continuaria sendo usada?','Would backpropagation remain in use?'],
    original:['O artigo pergunta se a retropropagação ainda teria lugar, diante de sua lentidão. É uma dúvida sobre o futuro do método, não uma previsão de que ele desapareceria.','The paper asks whether backpropagation would still have a place, given its slowness. It is a question about the method’s future, not a prediction that it would disappear.'],
    verdict:['O método continuou presente no treinamento','The method remained part of training'],
    now:['A ideia é usar o erro da resposta para calcular como ajustar as conexões anteriores. Redes como AlexNet e Transformer foram treinadas com gradientes obtidos por esse mecanismo. Computação, dados, arquiteturas e otimização também mudaram o que era viável.','The idea is to use an output error to calculate how earlier connections should change. Networks such as AlexNet and Transformer were trained using gradients obtained through this mechanism. Computing, data, architectures and optimization also changed what was feasible.'],
    limit:['Isso é sucesso de engenharia. Não prova que o cérebro aprenda do mesmo jeito.','That is an engineering success. It does not prove that the brain learns the same way.'],
    evidence:[['AlexNet · 2012','https://proceedings.neurips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html'],['Transformer · 2017','https://arxiv.org/abs/1706.03762']],
  },
  {
    label:['Generalizar','Generalization'], pages:'20, 21, 26',
    question:['O que o ajuste ao treino diz sobre dados novos?','What does fitting the training data tell us about new cases?'],
    original:['Os autores colocam o sobreajuste no centro da discussão: uma rede flexível pode se adaptar demais aos exemplos disponíveis. Validação e regularização são parte da resposta.','The authors put overfitting at the center of the discussion: a flexible network can adapt too closely to available examples. Validation and regularization are part of the response.'],
    verdict:['A relação entre tamanho e erro ganhou novas explicações','New explanations for the relationship between size and error'],
    now:['A segunda descida que acabamos de ver mostra um regime em que aumentar ainda mais o modelo melhora o teste. Ela amplia a história clássica; não apaga o risco de sobreajuste.','The second descent we just saw shows a regime in which making the model even larger improves test performance. It expands the classical story; it does not erase the risk of overfitting.'],
    limit:['O resultado depende do modelo, dos dados e do treinamento. Continuamos precisando de exemplos que o modelo não viu.','The result depends on the model, data and training. We still need examples the model has not seen.'],
    evidence:[['Double descent · 2019','https://doi.org/10.1073/pnas.1903070116'],['Overparameterized least squares · 2022','https://doi.org/10.1214/21-AOS2133']],
  },
  {
    label:['Simples ou complexo?','Simple or complex?'], pages:'5, 17–18, 20–21, 26',
    question:['Existe um método que ganha em qualquer dado?','Is there a method that wins on every kind of data?'],
    original:['O artigo insiste na comparação com alternativas estatísticas e questiona quando uma arquitetura complicada realmente se justifica.','The paper insists on comparison with statistical alternatives and asks when a complicated architecture is actually justified.'],
    verdict:['A comparação depende do problema e das condições','The comparison depends on the problem and conditions'],
    now:['Uma fotografia, um texto e uma planilha oferecem estruturas diferentes, que favorecem maneiras distintas de aprender. Comparações de 2022 encontraram bons resultados de árvores em vários conjuntos tabulares; trabalhos como TabPFN, de 2025, trouxeram novos resultados com redes nesse domínio. Por isso, uma conclusão sobre qual método funciona melhor precisa vir acompanhada das condições em que foi obtida.','Photographs, text and spreadsheets have different structures, which favor different ways of learning. Comparisons in 2022 found strong results for trees on several tabular datasets; work such as TabPFN in 2025 brought new neural-network results in that domain. A conclusion about which method works best therefore needs to include the conditions under which it was obtained.'],
    limit:['Essas referências não são um ranking atual de modelos. A métrica escolhida, o orçamento e a divisão dos dados também podem mudar a comparação.','These references are not a current model ranking. The chosen metric, budget and data split can also change the comparison.'],
    evidence:[['Tabular benchmarks · 2022','https://proceedings.neurips.cc/paper_files/paper/2022/file/0378c7692da36807bdec87ab043cdadc-Paper-Datasets_and_Benchmarks.pdf'],['TabPFN · 2025','https://www.nature.com/articles/s41586-024-08328-6']],
  },
  {
    label:['Entender a resposta','Understanding the answer'], pages:'18, 26',
    question:['Quando a previsão afeta alguém, acertar basta?','When a prediction affects someone, is accuracy enough?'],
    original:['Cheng e Titterington observam que a importância de interpretar um modelo depende da aplicação. Uma previsão útil nem sempre encerra a conversa.','Cheng and Titterington observe that the importance of interpreting a model depends on the application. A useful prediction does not always end the conversation.'],
    verdict:['A interpretação se tornou uma área de pesquisa própria','Interpretation developed into a research area'],
    now:['Recomendar um filme e apoiar uma decisão médica não têm a mesma consequência. Precisamos reconhecer falhas e saber quando confiar. Até uma imagem bonita que “explica” a rede pode não refletir o que ela realmente faz.','Recommending a film and supporting a medical decision do not have the same consequences. We need to recognize failures and know when to trust a result. Even an attractive image that “explains” a network may not reflect what it actually does.'],
    limit:['Explicar uma previsão não é provar uma causa. E uma explicação convincente não é necessariamente fiel ao modelo.','Explaining a prediction is not proving a cause. And a convincing explanation is not necessarily faithful to the model.'],
    evidence:[['Sanity checks · 2018','https://proceedings.neurips.cc/paper/2018/hash/294a8ed24b1ad22ec2e7efea049b8737-Abstract.html'],['Interpretable models · 2019','https://www.nature.com/articles/s42256-019-0048-x']],
  },
  {
    label:['A ponte com a física','The bridge to physics'], pages:'22–24, 26 · §5.2',
    question:['Como a física entra nessa história?','Where does physics enter this story?'],
    original:['A seção 5.2 discute conexões que já existiam: energia, redes de Hopfield, distribuições de Gibbs e máquinas de Boltzmann. O artigo apresenta essa ponte aos estatísticos.','Section 5.2 discusses connections that already existed: energy, Hopfield networks, Gibbs distributions and Boltzmann machines. The paper introduces this bridge to statisticians.'],
    verdict:['Uma relação anterior ao artigo, reconhecida depois','An earlier connection, recognized later'],
    now:['Hopfield e Hinton receberam o Nobel de Física de 2024 por trabalhos fundacionais que permitiram o aprendizado de máquina com redes neurais. A conexão com a física estatística é real. Mas a rede de Hopfield é de 1982, anterior ao artigo.','Hopfield and Hinton received the 2024 Nobel Prize in Physics for foundational work enabling machine learning with neural networks. The connection to statistical physics is real. But Hopfield’s network dates to 1982, before the paper.'],
    limit:['Reconhecer uma conexão importante não é prever um prêmio trinta anos depois.','Recognizing an important connection is not predicting a prize thirty years later.'],
    evidence:[['Hopfield · 1982','https://doi.org/10.1073/pnas.79.8.2554'],['Nobel · 2024','https://www.nobelprize.org/prizes/physics/2024/press-release/']],
  },
];

export function StoryHistory({locale}:{locale:'pt'|'en'}) {
  const lang=locale==='pt'?0:1;
  const t=(pt:string,en:string)=>locale==='pt'?pt:en;
  const [selected,setSelected]=useState(0);
  const j=judgments[selected];
  return <>
    <section className="story-section" id="judgments" aria-labelledby="judgments-title">
      <div className="story-prose"><p className="r-kicker">1994 → 2026</p><h2 id="judgments-title">{t('Então, o que eles acertaram?','So, what did they get right?')}</h2><p>{t('Os exemplos anteriores mostram duas relações que ajudam a reler o artigo: métodos diferentes podem compartilhar uma forma de decisão, e um bom ajuste no treino não basta para avaliar o aprendizado. Cheng e Titterington discutiam essas questões junto de outras, como a escolha da arquitetura e a interpretação das respostas. A comparação abaixo reúne cinco delas e acompanha os trabalhos posteriores que ajudam a entender o que mudou.','The previous examples show two connections that help us revisit the paper: different methods can share a decision rule’s form, and a good fit to training data is not enough to assess learning. Cheng and Titterington discussed these issues alongside others, such as architecture selection and interpreting predictions. The comparison below follows five of these questions through later work that helps explain what changed.')}</p><p>{t('O título da postagem usa a ideia de prever o futuro, mas o artigo não apresenta uma lista de previsões. Há perguntas em aberto, alertas e relações já conhecidas na época. Essa distinção importa para avaliar os autores sem atribuir a eles conclusões que não escreveram.','The headline uses the idea of predicting the future, but the paper does not present a list of predictions. It includes open questions, warnings and connections already known at the time. Keeping these distinctions matters if we want to assess the authors without attributing conclusions they did not write.')}</p></div>
      <div className="judgment-reader">
        <nav className="judgment-index" aria-label={t('Perguntas do artigo','Questions from the paper')}>{judgments.map((item,i)=><button key={item.pages} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>0{i+1}</span>{item.label[lang]}</button>)}</nav>
        <article className="judgment-copy" aria-live="polite">
          <p className="r-kicker">{t('No artigo','In the paper')} · p. {j.pages}</p><h3>{j.question[lang]}</h3><p>{j.original[lang]}</p>
          <div className="judgment-verdict"><span>{t('À luz do que veio depois','In light of what followed')}</span><h4>{j.verdict[lang]}</h4><p>{j.now[lang]}</p></div>
          <p className="judgment-limit">{j.limit[lang]}</p><div className="source-links"><a href="https://doi.org/10.1214/ss/1177010638" target="_blank" rel="noreferrer">{t('Artigo original','Original paper')} ↗</a>{j.evidence.map(([label,href])=><a key={href} href={href} target="_blank" rel="noreferrer">{label} ↗</a>)}</div>
        </article>
      </div>
      <div className="story-prose appendix-bridge"><a href="#evidence">{t('Além dessas cinco perguntas: ver os 17 temas e suas fontes','Beyond these five questions: explore all 17 themes and their sources')} ↓</a></div>
    </section>
    <MemoryDemo locale={locale}/>
    <section className="story-conclusion story-prose"><p className="r-kicker">{t('O que fica','What remains')}</p><h2>{t('O que essa leitura ajuda a entender hoje','What this reading helps us understand today')}</h2><p>{t('A relação entre estatística e redes neurais aparece em vários níveis. No exemplo das flores, ela está na forma da regra de decisão, apesar das diferenças no ajuste. Na comparação com dígitos, aparece na separação entre treino e teste e nas perguntas sobre generalização. Na rede de Hopfield, envolve estados, conexões e uma função de energia que permite acompanhar a recuperação de um padrão.','The relationship between statistics and neural networks appears at several levels. In the flower example, it lies in the form of the decision rule, despite differences in fitting. In the digit comparison, it appears in the separation of training and testing and the questions about generalization. In the Hopfield network, it involves states, connections and an energy function that lets us follow the recovery of a pattern.')}</p><p>{t('Ler o artigo com os resultados posteriores em vista ajuda a reconhecer tanto essa continuidade quanto as mudanças. Algumas técnicas ganharam novas aplicações, outras perguntas receberam respostas em condições específicas e várias continuam dependendo do problema estudado. Para entender uma rede, vale acompanhar não só o desenho, mas também os dados, o procedimento de treinamento e a avaliação que sustenta suas respostas.','Reading the paper alongside later results helps us recognize both continuity and change. Some techniques found new applications, some questions received answers under specific conditions, and others still depend on the problem being studied. Understanding a network means looking beyond its diagram to the data, training procedure and evaluation supporting its predictions.')}</p><a className="r-source-link" href="https://doi.org/10.1214/ss/1177010638" target="_blank" rel="noreferrer">{t('Voltar à fonte: Cheng & Titterington, 1994','Back to the source: Cheng & Titterington, 1994')} ↗</a></section>
  </>;
}

function MemoryDemo({locale}:{locale:'pt'|'en'}) {
  const t=(pt:string,en:string)=>locale==='pt'?pt:en;
  const [input,setInput]=useState(()=>damage());
  const [step,setStep]=useState(0);
  const frames=useMemo(()=>recover(input),[input]);
  const frame=frames[Math.min(step,frames.length-1)];
  const finished=step===frames.length-1;
  const matches=frame.state.every((v:number,i:number)=>v===memory[i]);
  const changeInput=(next:number[])=>{setInput(next);setStep(0)};
  const ex=(i:number)=>28+i/Math.max(1,frames.length-1)*300;
  const ey=(energy:number)=>24+(-energy/24)*108;
  return <section className="story-section" id="memory" aria-labelledby="memory-title">
    <div className="story-prose"><p className="r-kicker">{t('A física aparece no mecanismo','Physics shows up in the mechanism')}</p><h2 id="memory-title">{t('Como uma rede recupera um padrão','How a network recovers a pattern')}</h2><p>{t('A relação com a física fica mais concreta na rede de Hopfield, apresentada em 1982 e discutida no artigo de 1994. Aqui, as conexões são definidas para favorecer um padrão estável. Uma versão alterada desse padrão pode ser atualizada, pixel por pixel, até se aproximar da memória armazenada. Em vez de classificar uma imagem como no exemplo anterior, a rede modifica a própria configuração de entrada.','The connection to physics becomes more concrete in the Hopfield network, introduced in 1982 and discussed in the 1994 paper. Here, the connections are set to favor a stable pattern. An altered version of that pattern can be updated, pixel by pixel, toward the stored memory. Rather than classifying an image as in the previous example, the network changes the input configuration itself.')}</p><p>{t('Esse processo pode ser acompanhado por uma função chamada energia. Com as conexões simétricas e as atualizações de uma unidade por vez usadas aqui, ela não aumenta. Isso ajuda a explicar por que a rede chega a um estado estável, embora esse estado nem sempre seja o padrão que queríamos recuperar.','We can follow this process using a function called energy. With the symmetric connections and one-unit-at-a-time updates used here, it does not increase. This helps explain why the network settles into a stable state, although that state is not always the pattern we wanted to recover.')}</p></div>
    <div className="story-lab memory-lab">
      <header className="story-lab-heading"><h3>{t('Recuperando o desenho de um 2','Recovering the shape of a 2')}</h3><p>{t('Compare o padrão guardado com a entrada alterada. Você pode inverter pixels e acompanhar cada mudança da rede.','Compare the stored pattern with the altered input. You can flip pixels and follow each change made by the network.')}</p></header>
      <div className="memory-layout">
        <div className="memory-patterns">
          <figure><div className="pixel-grid stored-memory" aria-label={t('Padrão guardado: um 2 em uma grade de 7 por 7','Stored pattern: a 2 on a 7 by 7 grid')}>{memory.map((v:number,i:number)=><span key={i} className={v>0?'on':''}/>)}</div><figcaption>{t('Padrão guardado','Stored pattern')}</figcaption></figure>
          <figure><fieldset className="pixel-grid live-memory" aria-label={t('Pixels da entrada; clique para inverter','Input pixels; click to flip')}>{frame.state.map((v:number,i:number)=><button key={i} className={`${v>0?'on':''} ${frame.changed===i?'changed':''}`} aria-label={`${t('Linha','Row')} ${Math.floor(i/7)+1}, ${t('coluna','column')} ${i%7+1}`} aria-pressed={v>0} onClick={()=>changeInput(frame.state.map((p:number,k:number)=>k===i?-p:p))}/>)}</fieldset><figcaption aria-live="polite">{step===0?t('Entrada que você pode alterar','Input you can edit'):finished?t('Estado estável','Stable state'):t('Mudando um pixel por vez','Changing one pixel at a time')}</figcaption></figure>
        </div>
        <div className="memory-explanation"><p className="r-kicker">{t('Energia da rede','Network energy')}</p><p className="energy-number">{(frame.energy===0?0:frame.energy).toLocaleString(locale==='pt'?'pt-BR':'en',{maximumFractionDigits:1})}</p><svg viewBox="0 0 360 165" className="energy-chart" aria-label={t('Energia diminui a cada pixel corrigido','Energy decreases with each corrected pixel')}>{[0,-12,-24].map(v=><g key={v}><line x1="28" y1={ey(v)} x2="328" y2={ey(v)} className="story-grid"/><text x="22" y={ey(v)+4} textAnchor="end">{v}</text></g>)}<path d={frames.slice(0,step+1).map((f:{energy:number},i:number)=>`${i===0?'M':'L'}${ex(i)},${ey(f.energy)}`).join(' ')} className="energy-path"/><circle cx={ex(step)} cy={ey(frame.energy)} r="6"/><text x="28" y="162">0</text><text x="328" y="162" textAnchor="end">{frames.length-1}</text></svg><p>{t('Mudanças de pixels →','Pixel changes →')}</p><p aria-live="polite">{finished?(matches?t('Neste caso, a rede voltou ao padrão guardado.','In this case, the network returned to the stored pattern.'):t('Ela estabilizou em outro padrão. Energia menor não garante recuperar a memória que queríamos.','It settled into another pattern. Lower energy does not guarantee recovering the memory we wanted.')):t('A energia não é uma nota de acerto. É uma propriedade do estado e das conexões da rede.','Energy is not an accuracy score. It is a property of the network’s state and connections.')}</p></div>
      </div>
      <div className="memory-controls"><div className="story-actions"><button disabled={finished} onClick={()=>setStep(Math.min(step+1,frames.length-1))}>{t('Próxima mudança','Next change')} →</button><button disabled={finished} onClick={()=>setStep(frames.length-1)}>{t('Ver onde estabiliza','See where it settles')}</button><button onClick={()=>changeInput(damage())}>{t('Recomeçar','Start again')}</button><button onClick={()=>changeInput(damage(20))}>{t('E com muito mais ruído?','What about much more noise?')}</button></div><label id="memory-step">{t('Mudanças observadas','Observed changes')}: {step} / {frames.length-1}</label><Slider min={0} max={Math.max(1,frames.length-1)} value={[step]} step={1} disabled={frames.length===1} aria-labelledby="memory-step" onValueChange={v=>setStep(Math.min(frames.length-1,Array.isArray(v)?v[0]:v))}/></div>
      <details className="story-details"><summary>{t('O modelo por trás dos pixels','The model behind the pixels')}</summary><p>{t('Esta rede pequena tem 49 unidades, conexões simétricas e nenhuma auto-conexão. Os pesos foram construídos pela regra de Hebb para um único padrão. Atualizamos uma unidade por vez; em empate, preservamos seu estado. O gráfico usa os valores de energia calculados a cada mudança.','This small network has 49 units, symmetric connections and no self-connections. Weights were constructed with Hebb’s rule for one pattern. We update one unit at a time; a tie preserves its state. The chart uses the energy values calculated at each change.')}</p><p>{t('Guardar um único padrão simplifica muito o problema. A rede também tem outros estados estáveis, incluindo o padrão invertido; com ruído suficiente, pode ir para lá. Isso não é um reconhecedor geral de dígitos nem uma simulação do cérebro.','Storing one pattern greatly simplifies the problem. The network also has other stable states, including the inverted pattern; enough noise can take it there. This is neither a general digit recognizer nor a simulation of the brain.')}</p><a href="https://doi.org/10.1073/pnas.79.8.2554" target="_blank" rel="noreferrer">Hopfield, 1982 ↗</a></details>
    </div>
    <div className="history-bridge"><p><strong>1982</strong>{t('Hopfield publica a rede de memória.','Hopfield publishes the memory network.')}</p><p><strong>1994</strong>{t('Cheng e Titterington revisam a ponte com a física.','Cheng and Titterington review the bridge to physics.')}</p><p><strong>2024</strong>{t('O Nobel reconhece trabalhos de Hopfield e Hinton.','The Nobel recognizes work by Hopfield and Hinton.')}</p></div>
  </section>;
}
