'use client';

import { useState, useSyncExternalStore } from 'react';
import { Slider } from '@/components/ui/slider';
import data from '@/lib/story-data.json';

const subscribe=(callback:()=>void)=>{const media=window.matchMedia('(max-width:700px)');media.addEventListener('change',callback);return ()=>media.removeEventListener('change',callback);};
export const useCompactChart=()=>useSyncExternalStore(subscribe,()=>window.matchMedia('(max-width:700px)').matches,()=>false);

export function StoryGeneralization({locale}:{locale:'pt'|'en'}) {
  const t=(pt:string,en:string)=>locale==='pt'?pt:en;
  const [index,setIndex]=useState(4);
  const [guess,setGuess]=useState<number|null>(null);
  const guesses=[t('Vai continuar alto','It will stay high'),t('Vai cair de novo','It will fall again'),t('Não sei ainda','I am not sure')];
  const compact=useCompactChart();
  const row=data.curve[index];
  const revealed=guess!==null;
  const visible=data.curve.slice(0,revealed?22:12);
  const W=compact?360:820,H=compact?310:360,left=compact?40:52,right=W-20,bottom=H-40;
  const x=(p:number)=>left+Math.log(p/16)/Math.log(1280/16)*(right-left);
  const y=(err:number)=>bottom-err/.9*(bottom-28);
  const line=(key:'test_error_median'|'train_error_median')=>visible.map((d,i)=>`${i===0?'M':'L'}${x(d.width)},${y(d[key])}`).join(' ');
  const band=visible.map((d,i)=>`${i===0?'M':'L'}${x(d.width)},${y(d.test_error_q25)}`).join(' ')+' '+[...visible].reverse().map(d=>`L${x(d.width)},${y(d.test_error_q75)}`).join(' ')+' Z';
  const percent=(v:number)=>(v*100).toLocaleString(locale==='pt'?'pt-BR':'en',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
  return <section className="story-section" id="generalization" aria-labelledby="generalization-title">
    <div className="story-prose"><p className="r-kicker">{t('A pergunta que não desapareceu','The question that never went away')}</p><h2 id="generalization-title">{t('Acertar o que já viu é a parte fácil.','Getting familiar examples right is the easy part.')}</h2><p>{t('Uma regra pode funcionar nas flores usadas para construí-la e falhar na próxima flor. Por isso separamos exemplos de treino e de teste: aprendemos com um grupo e avaliamos no outro, que ficou de fora.','A rule can work on the flowers used to build it and fail on the next flower. That is why we separate training and test examples: learn from one group, evaluate on another that was left out.')}</p><p>{t('O artigo leva esse risco a sério. A intuição clássica é conhecida: flexibilidade de menos não captura o padrão; flexibilidade demais pode decorar particularidades. Mas o que acontece se continuarmos aumentando o modelo?','The paper takes this risk seriously. The classical intuition is familiar: too little flexibility misses the pattern; too much may memorize quirks. But what happens if we keep making the model larger?')}</p></div>
    <div className="story-lab descent-lab">
      <header className="story-lab-heading"><h3>{t('O mesmo teste. Modelos cada vez maiores.','The same test. Increasingly larger models.')}</h3><p>{t('Aqui usamos dígitos escritos à mão. Cada quadradinho é uma medida de intensidade; os 64 pixels viram a entrada do modelo.','Here we use handwritten digits. Each small square measures intensity; the 64 pixels become the model’s input.')}</p></header>
      <div className="digit-split">{(['train','test'] as const).map(group=><div key={group}><p><strong>{group==='train'?'300':t('1.497','1,497')}</strong> {group==='train'?t('para aprender','to learn from'):t('guardados para testar','held out for testing')}</p><div className="digit-strip">{data.digits[group].map(d=><figure key={d.index}><svg viewBox="0 0 8 8" shapeRendering="crispEdges" aria-label={`${t('Dígito real','Real digit')} ${d.label}`}>{d.pixels.map((v,i)=><rect key={i} x={i%8} y={Math.floor(i/8)} width="1" height="1" fill={`rgb(${255-v*12},${254-v*11},${249-v*12})`}/>)}</svg><figcaption>{d.label}</figcaption></figure>)}</div><small>{t('Seis imagens desse grupo; rótulos reais, não previsões.','Six images from this group; actual labels, not predictions.')}</small></div>)}</div>
      <div className="chart-heading"><span>{t('Dígitos classificados incorretamente (%) ↓ menor é melhor','Misclassified digits (%) ↓ lower is better')}</span><div className="story-legend"><span className="legend-a">━ {t('teste','test')}</span><span className="legend-green">┄ {t('treino','training')}</span></div></div>
      <figure className="descent-chart"><svg viewBox={`0 0 ${W} ${H}`} aria-labelledby="descent-chart-title"><title id="descent-chart-title">{t('Erro de treino e teste por largura do modelo. A faixa mostra o intervalo interquartil de dez inicializações.','Training and test error by model width. The band shows the interquartile range of ten initializations.')}</title>
        {[0,.2,.4,.6,.8].map(v=><g key={v}><line x1={left} y1={y(v)} x2={right} y2={y(v)} className="story-grid"/><text x={left-12} y={y(v)+5} textAnchor="end">{Math.round(v*100)}</text></g>)}
        {[16,128,300,1280].map(p=><text key={p} x={x(p)} y={H-12} textAnchor={p===1280?'end':p===16?'start':'middle'}>{p}</text>)}
        <line x1={x(300)} y1="28" x2={x(300)} y2={bottom} className="interpolation-marker"/>
        <path d={band} className="error-band"/><path d={line('test_error_median')} className="test-curve"/><path d={line('train_error_median')} className="train-curve"/>
        <line x1={x(row.width)} y1={y(row.test_error_median)} x2={x(row.width)} y2={bottom} className="selected-width"/>
        <circle cx={x(row.width)} cy={y(row.test_error_median)} r="7" className="selected-error"/>
      </svg><figcaption>{t('Características internas do modelo · escala logarítmica','Internal model features · logarithmic scale')}</figcaption></figure>
      <div className="descent-readout" aria-live="polite"><div><span>{t('Características','Features')}</span><strong>{row.width}</strong></div><div><span>{t('Erro no treino','Training error')}</span><strong>{percent(row.train_error_median)}</strong></div><div><span>{t('Erro no teste','Test error')}</span><strong className="test-value">{percent(row.test_error_median)}</strong></div></div>
      <div className="capacity-control"><label id="capacity-label">{t('Mude o tamanho do modelo','Change the model size')}</label><Slider min={0} max={revealed?21:11} step={1} value={[index]} aria-labelledby="capacity-label" onValueChange={v=>setIndex(Array.isArray(v)?v[0]:v)}/><div className="story-actions"><button onClick={()=>setIndex(4)}>128</button><button onClick={()=>setIndex(11)}>300</button>{revealed&&<button onClick={()=>setIndex(21)}>{t('1.280','1,280')}</button>}</div></div>
      <p className="curve-explanation" aria-live="polite">{row.width<300?t('Antes do pico, aumentar o modelo geralmente reduz os erros. Com 128 características, ele já classifica corretamente todos os exemplos de treino na mediana. Mesmo assim, erra cerca de um em cada dez dígitos novos.','Before the peak, a larger model generally reduces errors. At 128 features, the median training classification error is already zero. Yet it still gets roughly one in ten new digits wrong.'):row.width===300?t('Com 300 características, o erro de teste dispara. Aqui o modelo também consegue ajustar praticamente de forma exata os escores usados no treino. São duas noções diferentes de “acertar tudo”.','At 300 features, test error shoots up. Here the model also fits the training scores almost exactly. Those are two different meanings of “getting everything right”.'):t('Depois do pico, o erro em exemplos novos volta a cair. Nesta experiência, o modelo maior termina melhor que o melhor ponto anterior ao pico. É a segunda descida.','Past the peak, error on new examples falls again. In this experiment, the larger model ends up better than the best point before the peak. That is the second descent.')}</p>
      {!revealed?<div className="prediction-pause"><h3>{t('E depois de 300?','What happens after 300?')}</h3><p>{t('Antes de abrir o resto da curva: você acha que o erro em dígitos novos vai continuar alto ou voltar a cair?','Before opening the rest of the curve: do you think error on new digits will stay high or fall again?')}</p><div className="story-actions">{guesses.map((label,i)=><button key={i} onClick={()=>{setGuess(i);setIndex(21)}}>{label}</button>)}</div></div>:<div className="prediction-pause" aria-live="polite"><p className="r-kicker">Double descent</p><h3>{t('A curva tinha mais uma volta.','There was another turn in the curve.')}</h3><p>{t('Sua hipótese','Your guess')}: {guesses[guess]}. {t('Os dados desta experiência mostram uma segunda queda. Isso pode acontecer; não é uma lei de toda rede. Mais parâmetros não dispensam teste, regularização ou cuidado com os dados.','This experiment’s data show a second drop. It can happen; it is not a law for every network. More parameters do not remove the need for testing, regularization or careful data handling.')}</p><button onClick={()=>{setGuess(null);setIndex(4)}}>{t('Rever a pergunta','Revisit the question')}</button></div>}
      <details className="story-details"><summary>{t('Como fizemos — e o que não podemos concluir','How we did it — and what we cannot conclude')}</summary><p>{t('A linha é a mediana de dez inicializações; a faixa cobre os 50% centrais dos resultados. A divisão foi fixa: 300 imagens para treino, 1.497 para teste, sem sobreposição. Os números vêm do experimento local, não de uma curva desenhada à mão.','The line is the median of ten initializations; the band covers the middle 50% of results. The split was fixed: 300 training images, 1,497 test images, with no overlap. These numbers come from the local experiment, not a hand-drawn curve.')}</p><p>{t('O modelo tem uma camada ReLU aleatória e congelada. Só a saída linear é ajustada por mínimos quadrados de norma mínima. Em 128 características, o erro mediano de classificação no treino zera; em 300, a perda quadrática fica praticamente zero. A linha tracejada vertical marca esse segundo evento. Não treinamos uma rede profunda por retropropagação aqui.','The model has a random, frozen ReLU layer. Only the linear output is fitted by minimum-norm least squares. At 128 features, median training classification error reaches zero; at 300, squared loss becomes practically zero. The vertical dashed line marks this second event. We are not training a deep network by backpropagation here.')}</p><p>{t('Uma base pequena e uma única divisão não representam todos os problemas. O resultado demonstra um regime em que a segunda descida existe.','One small dataset and a single split do not represent every problem. The result demonstrates one regime in which the second descent exists.')}</p><div className="source-links"><a href="/data/double-descent.json" download>{t('Dados completos e configuração ↓','Full data and configuration ↓')}</a><a href={data.sources.digits} target="_blank" rel="noreferrer">Digits ↗</a><a href="https://doi.org/10.1073/pnas.1903070116" target="_blank" rel="noreferrer">Belkin et al., 2019 ↗</a></div></details>
    </div>
  </section>;
}
